### ISSUE TITLE
Errors in autoSync and getResevationsFromGmail

### ISSUE THREAD

**Issue by sverch** [jrunningen/amtrak2calendar#1]
Hey, thanks for making this script!  I tried to run it myself and I got these errors:

autoSync:

```
Head | autoSync | Web App | Jul 20, 2019, 11:40:28 AM | 98.853 s | Failed
-- | -- | -- | -- | -- | --

Stackdriver logs

Error | Jul 20, 2019, 11:42:07 AM | TypeError: Cannot call method "getContentType" of undefined.     at ocrAttachment(Ocr:12)     at autoSync(AutoSync:102)
-- | -- | --
```

getReservationsFromGmail:

```
Head | getReservationsFromGmail | Web App | Jul 20, 2019, 11:38:45 AM | 13.841 s | Failed
-- | -- | -- | -- | -- | --

Stackdriver logs

Error | Jul 20, 2019, 11:38:59 AM | TypeError: Cannot find function match in object GmailMessage.     at getReservationNumber(Reservation:7)     at [unknown function](AutoSync:85)     at getCancelledReservationNumbers(AutoSync:84)     at getReservationsFromGmail(AutoSync:139)
-- | -- | --
```

**Comment by jrunningen** [comment]
Sorry for the long response time! You're the first user I'm aware of that I don't know personally. The fix should be live on http://amtrak2calendar.runningen.net. Does it work for you now? Feel free to also test it on your own deployment.

**Comment by sverch** [comment]
Hey, no problem!  Thanks for the update, I know this is just a side thing.

Unfortunately I'm not able to try it right now, but this might not be because of the script:

![image](https://user-images.githubusercontent.com/788085/66706226-1b935700-ecfe-11e9-91b6-4ef8c558c41e.png)
